package exception_handling.labs;

/**
 * Exception Handling Exercise 6:
 *
 *      Demonstrate throwing an exception in one method and catching it in another method.
 *


class Demo6 {
    public static void genException() {
        int numer [] = {4,6,7,9};
        int denom [] = {9,3,2,};

        for (int i = 0, i <numer.length, i++) {

        }
    }
}

 **/
